### ISSUE TITLE
Layout doesn't look like the screenshot

### ISSUE THREAD

**Issue by troelsrichter** [gyurisc/BootstrapMVC#6]
Hello there. First of all great initiative, but I'm having some problems.

the layout looks like this in chrome and IE after cloning the project and building it:
http://dl.dropbox.com/u/1040055/temp/bootstrap.JPG

log on is not alligned right
header is too close to the menu bar
there is only two columns
there is no line at the buttom 
all buttons is the same color

when you click at the other menu items not all text is shown because it is placed under the menubar

**Comment by gyurisc** [comment]
Hi, thanks for the feedback! this is no good :) I never took the time and check out how this look like in IE. I will take a look and will reporrt back if I can solve this. I do not have too much experience in fixing this kind of problems though. 

Krisztian

**Comment by gyurisc** [comment]
If you can recommend how to fix this I would be more than happy to incorporate this in my project.

**Comment by elAndyG** [comment]
~~The other comment actually goes here lol sorry.~~
Youre missing a style in your _Layout.cshtml header.... Here's the fix

style type="text/css"
body {
padding-top: 60px;
padding-bottom: 40px;
}
/style

I uploaded an image to DropBox so you can see what im talking about since im having no luck pasting code here

http://dl.dropbox.com/u/20552993/fix.png

Here is also a link to a new _layout.cs that updates everything to a newer style... i also organized it to get the Container section into a newer section...

http://dl.dropbox.com/u/20552993/_Layout.cshtml

**Comment by gyurisc** [comment]
Hi Andy, Thanks for the fix. I will incorporate into the code. Krisztian

**Comment by gyurisc** [comment]
In order to post code you will need to place four space before the first code line, this way markdown knows that you are adding code :)

```
<style type="text/css">
    body {
        padding-top: 60px;
        padding-bottom: 40px;
    }
   </style>
```

**Comment by gyurisc** [comment]
I added your fix to the code file. Let me know if you have further problems :)
